use from_{ref,mut} to eliminate casts to pointers
hermit-os/loader pull request #272
Opened 2023-10-31 16:12 UTC by cagatay-y

As it stands, the PR requires `ptr_from_ref` and `strict_provenance` to land in stable. If the `ptr_from_ref` lands first, the branch can be updated to make use of the polyfill for the `pointer::addr` method in the sptr crate, as instructed in [its documentation](https://docs.rs/sptr/latest/sptr/#applying-the-overlay).

2024-02-07 15:36 UTC, mkroening commented
@cagatay-y, `ptr_from_ref` will be stable with tomorrow's 1.76.0 release.

2024-02-20 10:20 UTC, mkroening requested changes
`ptr_from_ref` is now stable. :)

2024-02-22 10:45 UTC, mkroening requested changes
Let's replace all instances of `ptr::from_ref(unsafe {&foo})` with `ptr::addr_of!(foo)`.

2024-02-22 13:11 UTC, mkroening requested changes
Same for replacing `ptr::from_ref(unsafe {&mut foo})` with `ptr::addr_of_mut!(foo)`.

2024-02-22 13:24 UTC, cagatay-y commented
Do you mean the ones inside a `from_raw_parts_mut`? We have to have an unsafe block for `from_raw_parts_mut` in that case. Of course, I can convert them too, I am asking to make sure I am not missing something else.

2024-02-22 13:26 UTC, mkroening commented
> Do you mean the ones inside a `from_raw_parts_mut`? We have to have an unsafe block for `from_raw_parts_mut` in that case. Of course, I can convert them too, I am asking to make sure I am not missing something else.

Yeah. While the amount of unsafe blocks stays the same in those cases, the amount of unsafe operations would be less. And it would be more consistent with the rest of the code.

2024-02-22 14:34 UTC, mkroening requested changes
Sorry for not catching this earlier, but can we also enable the corresponding lint?
https://rust-lang.github.io/rust-clippy/master/index.html#ref_as_ptr

2024-02-22 14:55 UTC, cagatay-y commented
I can't get the lint to work on my machine. It complains that no such lint exists. I am version on 0.1.77. Does it work for you?

2024-02-22 15:05 UTC, mkroening commented
> I can't get the lint to work on my machine. It complains that no such lint exists. I am version on 0.1.77. Does it work for you?

Ah, true. This will be in Rust 1.77.0, but the current stable is 1.76.0.

2024-02-22 15:05 UTC, mkroening approved these changes
Thanks!

2024-02-22 15:13 UTC, merged