Add alloc support
hermit-os/loader pull request #278
Opened 2023-11-30 18:28 UTC by duanyu-yu

Added alloc support for loader, based on the previous bootstrap and bump allocator implementations from the kernel.

2023-11-30 22:04 UTC, mkroening requested changes
Thanks a lot, Yu! :)

Overall, this looks very promising. I left a few comments with the hope to avoid a few dependencies as well as `nightly`.

2023-11-30 22:04 UTC, mkroening commented on src/main.rs
> +#![feature(allocator_api)]
I'd really like to avoid having to use `nightly` in this project.

Instead, we could use [allocator-api2], which provides the same API in a crate.

[allocator-api2]: https://github.com/zakarumych/allocator-api2

2023-11-30 22:04 UTC, mkroening commented on src/allocator/mod.rs
> +	heap: Option<Talc<ErrOnOom>>,
I think we can remove this altogether, since we only want the bootstrap allocator here.
That also means we don't need the talc dependency and can simplify this abstraction level a lot.

2023-11-30 22:04 UTC, mkroening commented on src/allocator/mod.rs
> +//! Implementation of the HermitCore Allocator for dynamically allocating heap memory
Nit: It's just Hermit not HermitCore nowadays.

2023-11-30 22:04 UTC, mkroening commented on Cargo.toml
> +crossbeam-utils = { version = "0.8", default-features = false }
Nit: let's keep these sorted alphabetically.

2023-11-30 22:04 UTC, mkroening commented on src/allocator/mod.rs
> +pub struct LockedAllocator(InterruptTicketMutex<GlobalAllocator>);
We can use [`spinning_top::Spinlock`](https://docs.rs/spinning_top/0.3.0/spinning_top/index.html) here. We don't need fairness (ticket lock) or communicate with interrupts.

2023-11-30 22:04 UTC, mkroening commented on src/allocator/bootstrap.rs
> +use hermit_sync::ExclusiveCell;
We can use [`exclusive_cell::ExclusiveCell`](https://docs.rs/exclusive_cell/0.1.0/exclusive_cell/index.html) directly here. We don't need all the other types from hermit-sync and can reduce dependencies.

2023-11-30 22:04 UTC, mkroening commented on src/allocator/mod.rs
> +	}
We can skip overaligning here, since there will never be contention on the allocations. This way we can also avoid the crossbeam-utils dependency.

2023-12-01 14:52 UTC, duanyu-yu commented on src/allocator/mod.rs
> +	heap: Option<Talc<ErrOnOom>>,
Do you mean that we don't need a heap at all? Or we just define a heap in other way?

2023-12-01 15:20 UTC, mkroening commented on src/allocator/mod.rs
> +	heap: Option<Talc<ErrOnOom>>,
We don't need this `heap: Option<Talc<ErrOnOom>>` at all. It's currently never initialized or used anyway. For allocations in the loader, `bootstrap_allocator` with a fixed size should be enough.

2024-01-10 14:01 UTC, mkroening requested changes
Thanks a lot!

Code-wise, this looks excellent. Just a few more requests on the form:

- The `Cargo.lock` file should not be added to `.gitignore`. Instead, it should track the minimum changes necessary by this PR.
- This PR should not include any merge commits. In this case, we might even squash everything into one commit.
- The formatting CI check fails (run `cargo fmt`) to fix any formatting issues.

If you need help with rebasing, reach out. :)

2024-01-11 09:42 UTC, mkroening requested changes
Ah, CI shows that this does not work on UEFI, which makes sense, since UEFI already provides a global allocator.

Let's move the dependencies in `Cargo.toml` to `[target.'cfg(target_os = "none")'.dependencies]` and mark `mod allocator;` with `#[cfg(target_os = "none")]`. We could move the declaration of the global allocator into the `allocator` module, too.

2024-01-12 14:29 UTC, mkroening approved these changes
Thanks, this looks good to me! :)

2024-01-12 14:34 UTC, merged